name: CI/CD Spark Agent Deploy
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
 
      - name: Lint with Flake8
        run: |
          pip install flake8
          # Syntax check only to avoid local version conflicts
          python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
 
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}
 
      - name: Upload Spark Job to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: wordcount_health.py
          destination: agentic-elt-dataproc/jobs/
